import { IPostPreview } from './post';
import { IUserPreview } from './user';

export interface ICommentCreateRequest {
  message: string; // (length: 2-500)
  owner: IUserPreview['id']; // (User Id)
  post: IPostPreview['id']; // (Post Id)
}

export interface IComment {
  id: string; // (autogenerated)
  message: string; // (length: 2-500)
  owner: IUserPreview; // (User Preview)
  post: IPostPreview['id']; // (Post Id)
  publishDate: string; // (autogenerated)
}
